version = 1
SPDX-PackageName = "qgiflib"
SPDX-PackageSupplier = "Igor Mironchik <igor.mironchik@gmail.com>"
SPDX-PackageDownloadLocation = "https://github.com/igormironchik/qgiflib"

[[annotations]]
path = [".github/**", ".gitignore", ".gitmodules", "README.md", "CMakeLists.txt", "**/**.txt", "**/**.ico", "**/**qrc", "**/**.rc", "**/**.ui", "**/**.md", "**/**.cfgfile", "**/**.ts", "**/**.qm", "**/**.xml", "REUSE.toml"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2023-2024 Igor Mironchik <igor.mironchik@gmail.com>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "3rdparty/giflib/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "1997  Eric S. Raymond"
SPDX-License-Identifier = "MIT"
